Drama: Add systemd (as recomended), and start using a test suite

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -5,7 +5,7 @@
 # found in the copyright file.
 set -e
 
-function add_debian_repository {
+function add_debian_repository() {
   echo "** Adding Utappia public key"
   apt-key adv --keyserver keyserver.ubuntu.com --recv EBC8F9FD
   echo "** Adding Debian repository"
@@ -29,6 +29,10 @@ else
   fi
 fi
 
+#if [[ -x "$(command -v  systemctl )" ]]; then
+#  echo "** Enable systemd services"
+#  systemctl enable ucaresystem-automation-cleanup.service || true
+#fi
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
