remove-old-kernels help text and config file

diff --git a/scripts/remove-old-kernels b/scripts/remove-old-kernels
--- a/scripts/remove-old-kernels
+++ b/scripts/remove-old-kernels
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 #    remove-old-kernels - remove old kernel packages
 #    Copyright (C) 2012 Dustin Kirkland <kirkland@ubuntu.com>
@@ -20,23 +20,32 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# Ensure we're running as root
-if [ "$(id -u)" != 0 ]; then
-	echo "ERROR: This script must run as root.  Hint..." 1>&2
-	echo "  sudo $0 $@" 1>&2
-	exit 1
+#Config file
+if [ -x "/etc/ucaresystem.conf" ]; then
+  source /etc/ucaresystem.conf
 fi
-
 # NOTE: This script will ALWAYS keep the currently running kernel
-# NOTE: Default is to keep 2 more, user overrides with --keep N
-KEEP=2
-# NOTE: Any unrecognized option will be passed straight through to apt-get
+# NOTE: Default is to keep 2 more, user overrides with --keep N, or change in the config file
+KEEP_KERNELS=${KEEP_KERNELS:=2}
+
+function action_help {
+  echo "$(basename "${0}"): remove old kernels tool."
+  echo "OPTIONS"
+  echo "  -h|--help this help text"
+  echo "  -k <n>|--keep=<n> keep <n> kernels"
+  echo "Any unrecognized option will be passed straight through to apt-get"
+  exit
+}
+
 APT_OPTS=
 while [ ! -z "$1" ]; do
 	case "$1" in
-		--keep)
+		-h | --help)
+		action_help
+		;;
+		-k | --keep)
 			# User specified the number of kernels to keep
-			KEEP="$2"
+			KEEP_KERNELS="$2"
 			shift 2
 		;;
 		*)
@@ -46,12 +55,19 @@ while [ ! -z "$1" ]; do
 	esac
 done
 
+# Ensure we're running as root
+if [ "$(id -u)" != 0 ]; then
+	echo "ERROR: This script must run as root.  Hint..." 1>&2
+	echo "  sudo $0 $@" 1>&2
+	exit 1
+fi
+
 # Build our list of kernel packages to purge
 if [ $(uname -r|grep pve) ]; then
-   CANDIDATES=$(ls -tr /boot/vmlinuz-* | head -n -${KEEP} | grep -v "$(uname -r)$" | cut -d- -f2- | awk '{print "pve-kernel-" $0 " pve-headers-" $0}' )
+   CANDIDATES=$(ls -tr /boot/vmlinuz-* | head -n -${KEEP_KERNELS} | grep -v "$(uname -r)$" | cut -d- -f2- | awk '{print "pve-kernel-" $0 " pve-headers-" $0}' )
    REMOVED=$(dpkg -l| grep ^rc | awk '{print $2}' | grep -e pve-kernel -e pve-keaders)
 else
-   CANDIDATES=$(ls -tr /boot/vmlinuz-* | head -n -${KEEP} | grep -v "$(uname -r)$" | cut -d- -f2- | awk '{print "linux-image-" $0 " linux-headers-" $0}' )
+   CANDIDATES=$(ls -tr /boot/vmlinuz-* | head -n -${KEEP_KERNELS} | grep -v "$(uname -r)$" | cut -d- -f2- | awk '{print "linux-image-" $0 " linux-headers-" $0}' )
    REMOVED=$(dpkg -l| grep ^rc | awk '{print $2}' | grep -e linux-image -e linux-keaders)
    OLD_HEADERS=$(dpkg -l|grep linux-headers | grep -v $(ls -tr /boot/vmlinuz-* | sed -e "s/^\/boot\/vmlinuz-/-e /" -e "s/-generic$//" | tr '\n' ' ') -e generic | awk '{print $2}')
 fi
