command line options

diff --git a/scripts/ucaresystem b/scripts/ucaresystem
--- a/scripts/ucaresystem
+++ b/scripts/ucaresystem
@@ -36,6 +36,7 @@ AUTO_REBOOT=${AUTO_REBOOT:=false}
 AUTO_REBOOT_TIMEOUT=${AUTO_REBOOT_TIMEOUT:=10}
 ASK_CONFIRM=${ASK_CONFIRM:=true}
 EXEC=""
+DO_WAIT=false
 
 ## Colors
 RED=""
@@ -71,7 +72,7 @@ else
 fi
 
 trap trap_handler 1 2 3 6
-function trap_handler {
+function trap_handler() {
   { set +x; } 2>/dev/null
   banner "Program interrupt."
   echo "  The program have stop before finished. Your system maybe in an incomplete state."
@@ -84,39 +85,48 @@ function banner() {
   echo -e "${GREEN}${BOLD}***${BOLDOFF} ${1}${NORMAL}"
 }
 
-function ask_yesno {
+function ask_yesno() {
   prompt=$1
   set -- $(${LOCALE} LC_MESSAGES)
-  yesptrn="$1"; noptrn="$2"; yesword="$3"; noword="$4"
+  yesptrn="$1"
+  noptrn="$2"
+  yesword="$3"
+  noword="$4"
   while true; do
     read -rp "${prompt} (${yesword} / ${noword})? " yn
     case $yn in
-        ${yesptrn##^} ) response="yes"; break ;;
-        ${noptrn##^} ) response="no"; break ;;
-        * ) echo "${prompt} ${yesword} / ${noword}.";;
+    ${yesptrn##^})
+      response="yes"
+      break
+      ;;
+    ${noptrn##^})
+      response="no"
+      break
+      ;;
+    *) echo "${prompt} ${yesword} / ${noword}." ;;
     esac
-done
+  done
 }
 
-function check_eol {
+function check_eol() {
   distribution_id=$(${LSB_RELEASE} --id | cut -f2)
   codename=$(${LSB_RELEASE} --codename | cut -f2)
 
-#  distribution_id="Ubuntu" && codename="focal"
+  # distribution_id="Ubuntu" && codename="focal"
 
   valid_ids=("Debian" "Ubuntu")
   if [[ ! "${valid_ids[*]}" == *"${distribution_id}"* ]]; then
-    banner "Your distribution '${distribution_id}', codename:'${codename}' is unsupported."
-    exit
+    banner "Your distribution is '${distribution_id}', codename:'${codename}'."
+    return
   fi
 
   case "${distribution_id}" in
-    "Debian" )  DISTRO_INFO="/usr/bin/debian-distro-info" ;;
-    "Ubuntu" )  DISTRO_INFO="/usr/bin/ubuntu-distro-info" ;;
+  "Debian") DISTRO_INFO="/usr/bin/debian-distro-info" ;;
+  "Ubuntu") DISTRO_INFO="/usr/bin/ubuntu-distro-info" ;;
   esac
 
   supported_distro=$(${DISTRO_INFO} --supported)
-  days=$(${DISTRO_INFO} --series=${codename} --days)
+  days=$(${DISTRO_INFO} --series="${codename}" --days)
 
   if [[ "${supported_distro[*]}" == *"${codename}"* ]]; then
     banner "Your distribution '${GREEN}${distribution_id}${NORMAL}', codename:'${GREEN}${codename}${NORMAL}' is not at eol."
@@ -130,14 +140,14 @@ function check_eol {
     return
   else
     banner "Your distribution '${distribution_id}', codename:'${codename}' is reach the end of support"
-    echo  "  The end of support was before ${days//-/} days."
-    echo  "  Please upgrade your distribution to a latest release!"
-    echo  "  Try run: $(basename "${0}") --upgrade"
+    echo "  The end of support was before ${days//-/} days."
+    echo "  Please upgrade your distribution to a latest release!"
+    echo "  Try run: $(basename "${0}") --upgrade"
     exit
   fi
 }
 
-function check_root_priv {
+function check_root_priv() {
   # Checking if the user has run the script with "sudo" or not
   if [[ $EUID -ne 0 ]]; then
     echo -ne "${RED}${BOLD}Error: ${BOLDOFF} '$0'" 1>&2
@@ -177,17 +187,17 @@ function welcome_screen() {
   if [ "${ASK_CONFIRM}" == "true" ]; then
     ask_yesno "Are you sure ?"
     if [[ "${response}" == "no" ]]; then
-        exit 1
+      exit 1
     fi
   fi
 }
 
-function action_version {
+function action_version() {
   echo "$(basename "${0}") version ${UCARE_VERSION}"
   exit
 }
 
-function action_maintain {
+function action_maintain() {
   check_root_priv
   banner "Start System update actions"
 
@@ -208,7 +218,7 @@ function action_maintain {
   sleep ${WAIT_ACTION}
 }
 
-function action_clenaup {
+function action_clean() {
   check_root_priv
   banner "Start Cleanup actions"
   ## Removes unneeded packages
@@ -221,7 +231,7 @@ function action_clenaup {
   ## Removes unused config files
   banner "Removing unused config files"
   set -x
-  ${EXEC} ${SUDO} ${DEBORPHAN} -n --find-config |  ${EXEC}  xargs ${SUDO} ${APT} -y --purge autoremove
+  ${EXEC} ${SUDO} ${DEBORPHAN} -n --find-config | ${EXEC} xargs ${SUDO} ${APT} -y --purge autoremove
   { set +x; } 2>/dev/null
   sleep ${WAIT_ACTION}
 
@@ -282,7 +292,59 @@ EOT
   sleep ${WAIT_ACTION}
 }
 
+function action_upgrade() {
+  distribution_id=$(${LSB_RELEASE} --id | cut -f2)
+  codename=$(${LSB_RELEASE} --codename | cut -f2)
+
+  case "${distribution_id}" in
+  "Debian") do_debian_upgade "$1" ;;
+  "Ubuntu") do_ubuntu_upgade "$1" ;;
+  "LinuxMint")
+    echo "Linux Mint is unsupported. Please use the distro tool"
+    exit
+    ;;
+  *)
+    echo "Your distribution '${distribution_id}' is unsupported. Please do a pull request."
+    exit
+    ;;
+  esac
+
+}
+
+function do_ubuntu_upgrade() {
+  action="$1"
+  # Always ask
+  ask_yesno "Are you sure ?"
+  if [[ "${response}" == "no" ]]; then
+    exit 1
+  fi
+
+  case "$action" in
+    "next" )
+      action_upgrade_next
+      ;;
+    "development" )
+      action_upgrade_devel
+      ;;
+    "eol" )
+      action_upgrade_EOL
+      ;;
+    * )
+      echo "Error: unknown upgrade tag '$action'"
+      ;;
+  esac
+}
+
+function do_debian_upgrade() {
+  echo "TODO"
+}
+
 function action_upgrade_next() {
+  if [ -x ${UPDATE_TOOL} ]; then
+    echo "Error missing ${UPDATE_TOOL}"
+    exit 1
+  fi
+
   check_root_priv
   banner "Upgrade to next Release"
   ${EXEC} ${UPDATE_TOOL}
@@ -291,160 +353,126 @@ function action_upgrade_next() {
 }
 
 function action_upgrade_devel() {
+  if [ -x ${UPDATE_TOOL} ]; then
+    echo "Error missing ${UPDATE_TOOL}"
+    exit 1
+  fi
   check_root_priv
   ${EXEC} ${UPDATE_TOOL} -d
   banner "Done upgrade to next Release"
   sleep ${WAIT_ACTION}
 }
 
-function action_help {
+function action_help() {
   cat <<EOF
-	
 uCareSystem Core $UCARE_VERSION : All-in-one system update and maintenance tool
 
 Usage:
-  sudo ucaresystem [--mode=name] [mode-options]
+  sudo ucaresystem [options]
   ucaresystem --help|--version
 
-See man page for more info
-
-OPTIONS
-  -m name, --mode=name
-    Choose mode of operation. Valid modes are "maintain", "upgrade","cleanup"
-    If no option is given "maintain" mode will be used (configurable)
-
+MODES
+   -m, --maintenance
+      Do normal maintenance jobs. The default action id no option is given.
+   -c, --clean
+      reclaim some disk space
+   -u type, --upgrade=type
+          Upgrade ...
+OTHER OPTIONS
   -n, --dyrun
     Show only the commands, but do not modify the system
-
   -y, --yes
     Don't ask for confirmation
-
   -h, --help
     Display this help text
-
   -v, --version
     Display program version and exits
-
   -s, --skip
     Do not show the welcome banner, and do not pause.
-
   -w, --wait
-          Press ENTER to end the program. For the "gui" version
+    Press ENTER to end the program. For the "gui" version
 
-
-   -u, --upgrade
-          Upgrade to next available release
-
-   -d, --development
-          Upgrade to a development release. For testers and developers only
-
-   -e, --eol
-          If your Ubuntu (and official flavors) has reached the EOL support you can upgrade to the next supported  release.   This  option  is  for  Ubuntu
-          releases that have reached their EOL and the user wants to upgrade it to the next supported version.
-
-
-
-   -m, --maintenance
-          Do normal maintenance jobs. The default action id no option is given.
-
+See man page for more info
 EOF
+  exit
 }
 
 ##
 ## The main process starts here
 ##
 
-DO_WELCOME_SCREEN=true
-DO_REMOVE_KERNELS=true
-DO_action_help=false
-DO_MAINTENACE=true
-DO_UPGRADE_TO_NEXT_RELEASE=false
-DO_UPGRADE_TO_DEVEL_RELEASE=false
-DO_UPGRADE_EOL_TO_NEXT=false
-DO_WAIT=false
-
-ARGS=$(getopt -o hnsudewmyv --long help,dryrun,skip,upgrade,development,eol,wait,maintenance,yes,version -- "$@")
+MODE="${DEFAULT_MODE}"
+UPGRADE_MODE="next"
+ARGS=$(getopt -o hvdysmcwu: --long help,version,dryrun,yes,skip,maintain,clean,wait,upgrade: -- "$@")
 eval set -- "$ARGS"
 
 while true; do
   case "$1" in
   -h | --help)
-    DO_action_help=true
+    action_help
     shift
     ;;
-  -n | --dryrun)
-    EXEC="echo"
-    shift
-    ;;
-  -y | --yes )
-    ASK_CONFIRM=false
-    shift
-    ;;
-  -v | --version )
+  -v | --version)
     action_version
     shift
     ;;
+  -d | --dryrun)
+    EXEC="echo"
+    shift
+    ;;
+  -y | --yes)
+    ASK_CONFIRM=false
+    shift
+    ;;
   -s | --skip)
-    DO_WELCOME_SCREEN=false
-    shift
-    ;;
-  -u | --upgrade)
-    DO_UPGRADE_TO_NEXT_RELEASE=true
-    shift
-    ;;
-  -d | --development)
-    DO_UPGRADE_TO_DEVEL_RELEASE=true
-    shift
-    ;;
-  -e | --eol)
-    DO_UPGRADE_EOL_TO_NEXT=true
+    SHOW_BANNER=false
     shift
     ;;
   -w | --wait)
     DO_WAIT=true
     shift
     ;;
-  -m | --maintenance)
-    DO_MAINTENACE=true
+  -m | --maintain)
+    MODE=maintain
     shift
     ;;
-  --)
+  -c | --clean)
+    MODE=clean
     shift
-    break
+    ;;
+  -u | --upgrade)
+    MODE=upgrade
+    UPGRADE_MODE="$2"
+    shift
+    shift
     ;;
   *) break ;;
   esac
 done
 
-if [ "$DO_action_help" == true ]; then
-  action_help
-  exit
-fi
-
 if [ "$SHOW_BANNER" == true ]; then
   welcome_screen
 fi
 
-if [ "$DO_MAINTENACE" == true ]; then
+case "$MODE" in
+"maintain")
+  check_eol
   action_maintain
-fi
-
-if [ "$DO_UPGRADE_TO_NEXT_RELEASE" == true ]; then
-  action_upgrade_next
-fi
-
-if [ "$DO_UPGRADE_TO_DEVEL_RELEASE" == true ]; then
-  action_upgrade_devel
-fi
-
-if [ "$DO_UPGRADE_EOL_TO_NEXT" == true ]; then
-  action_upgrade_EOL
-fi
+  action_clean
+  ;;
+"clean")
+  check_eol
+  action_clean
+  ;;
+"upgrade")
+  action_upgrade "${UPGRADE_MODE}"
+  ;;
+esac
 
 check_reboot
 banner "Done"
 
 if [ "$DO_WAIT" == true ]; then
   echo
-  read -r -p "Press enter to close the window" response
+  read -r -p "Press enter to close the window"
 fi
